### ISSUE TITLE
ROS_monodepth.py is missing,where can download this code now? 

### ISSUE THREAD

**Issue by cudnn** [DGIST-ARTIV/dgist-artiv.github.io#1]

**Comment by shinkansan** [comment]
We haven't released the entire GitHub yet. Later, we will unveil the entire framework of our self-driving system. 

If you write down the email, we will give you the monodepth ros implementation version. But our team decided not to use monodepth for autonomous driving, so the version on the blog is the latest.

**Comment by cudnn** [comment]
978917153@qq.com

**Comment by cudnn** [comment]
978917153@qq.com

**Comment by 99sphere** [comment]
I sent the ROS_monodepth.py file to the email you wrote above, so check it out. If you have a problem, feel free to contact me.

**Comment by emad555** [comment]
Can you please send me the code to my email:
emadomari40@gmail.com

**Comment by 99sphere** [comment]
I sent it.
